# Before issuing `kubectl apply` command,
# modify the value contains "<" and ">" to correct value

# namespace-deploy.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: <NAMESPACE_NAME>

---
# cert-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cert-secrets
  namespace: <NAMESPACE_NAME>
type: tls
data:
  tls.crt: |-
    <TLS_CERT_WITH_B64_ENCODED>
  tls.key: |-
    <TLS_KEY_WITH_B64_ENCODED>

---
# auth-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: <NAMESPACE_NAME>
type: generic
data:
  htpasswd: >-
    <HTPASSWD_CONTENT_WITH_B64_ENCODED>

---
# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: podman-registry-pv
spec:
  capacity:
    storage: <SIZE_OF_PV>
  hostPath:
    path: /var/lib/registry
  accessModes:
    - ReadWriteOnce

---
# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podman-registry-pvc
  namespace: <NAMESPACE_NAME>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # This value must less then or equal to persistent volumes total size
      storage: <SIZE_OF_PVC>

---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REGISTRY_APP_NAME>
  namespace: <NAMESPACE_NAME>
  labels:
    app_name: <REGISTRY_APP_NAME>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app_name: <REGISTRY_APP_NAME>
  template:
    metadata:
      labels:
        app_name: <REGISTRY_APP_NAME>
    spec:
      volumes:
        - name: repository-volume
          persistentVolumeClaim:
            claimName: podman-registry-pvc
        - name: certificates-volume
          secret:
            secretName: cert-secrets
            items:
              - key: tls.crt
                path: ./tls.crt
              - key: tls.key
                path: ./tls.key
        - name: authorization-volume
          secret:
            secretName: auth-secrets
      containers:
        - name: <REGISTRY_APP_NAME>
          image: docker.io/registry:latest
          ports:
            - hostPort: 5000
              containerPort: 5000
              protocol: TCP
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATES
              value: /var/lib/registry/certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /var/lib/registry/certs/tls.key
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: basic_realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /var/lib/registry/auth/htpasswd
          volumeMounts:
            - name: repository-volume
              mountPath: /var/lib/registry
              subPath: registry
            - name: certificates-volume
              readOnly: true
              mountPath: /var/lib/registry/certs
            - name: authorization-volume
              mountPath: /var/lib/registry/auth
          imagePullPolicy: Always

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: <REGISTRY_APP_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app_name: <REGISTRY_APP_NAME>
  type: ClusterIP
